<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="CreateCustomerSanityRun" duration-ms="1931" started-at="2017-11-04T11:07:05Z" finished-at="2017-11-04T11:07:06Z">
    <groups>
      <group name="sanity">
        <method signature="CreateCustomer.createCustomerWithValidData(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.selenium.createCustomer.CreateCustomer@402a079c]" name="createCustomerWithValidData" class="com.selenium.createCustomer.CreateCustomer"/>
      </group> <!-- sanity -->
      <group name="login">
        <method signature="CreateCustomer.createCustomerWithValidData(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.selenium.createCustomer.CreateCustomer@402a079c]" name="createCustomerWithValidData" class="com.selenium.createCustomer.CreateCustomer"/>
      </group> <!-- login -->
    </groups>
    <test name="CreateCustomer" duration-ms="1931" started-at="2017-11-04T11:07:05Z" finished-at="2017-11-04T11:07:06Z">
      <class name="com.selenium.createCustomer.CreateCustomer">
        <test-method status="FAIL" signature="createCustomerWithValidData(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.selenium.createCustomer.CreateCustomer@402a079c]" name="createCustomerWithValidData" duration-ms="1868" started-at="2017-11-04T16:37:05Z" data-provider="createCustomerData" finished-at="2017-11-04T16:37:06Z">
          <exception class="org.testng.internal.reflect.MethodMatcherException">
            <message>
              <![CDATA[
Data provider mismatch
Method: createCustomerWithValidData([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=3, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String)nadi,(java.lang.String)muthu,(java.lang.String)09/29/1989]]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: createCustomerWithValidData([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=3, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String)nadi,(java.lang.String)muthu,(java.lang.String)09/29/1989]
	at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:52)
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1278)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1171)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.reflect.MethodMatcherException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createCustomerWithValidData -->
      </class> <!-- com.selenium.createCustomer.CreateCustomer -->
    </test> <!-- CreateCustomer -->
  </suite> <!-- CreateCustomerSanityRun -->
</testng-results>
